CREATE DATABASE SQL_ASSIGNMENT;
USE SQL_ASSIGNMENT;
CREATE TABLE EMP (EMP_NO INT, EMP_NAME VARCHAR(30), JOB VARCHAR(30), MGR INT,
HIRE_DATE DATE, SALARY FLOAT, DEPT_NO INT);

CREATE TABLE DEPT (DEPT_NO INT , DEPT_NAME VARCHAR(15), LOCATION VARCHAR(15));

CREATE TABLE SALGRD (SALARY_GRD INT, LOW_SALARY FLOAT, HIGH_SALARY FLOAT);

INSERT INTO EMP values (1, "Mahesh J","Clerk",115, "20-03-2024", 202032.34,101 );