# SEPT 19 Onwards, all here.

USE empDB;

SET AUTOCOMMIT = 0;

SELECT * FROM EMP;

SELECT COUNT(EID) FROM EMP;
	
INSERT INTO emp VALUES
(3024, 'Bittu',"Mumbai", "MLE",2939502),
(3025, 'Shiwam',"Bhayculla", "SE",459502),
(3026, 'Arnav',"Kalyan", "MLE",452402),
(3027, 'Vibar',"Thane", "SE",439502),
(3028, 'Tirth',"Parel", "MLE",5329502),
(3029, 'Krishna',"Santacruz", "SE",4439502),
(3030, 'Sam',"CST", "MLE",2529502);

UPDATE emp set dept = "MLE" where eid =3021;

COMMIT;

ROLLBACK;


-- SAVE TRANSACTIONS

START TRANSACTION;
DELETE FROM EMP WHERE CITY = "CST";
SAVEPOINT A;

UPDATE EMP SET SALARY = 30000 WHERE EID = 3015;
SAVEPOINT B;

DELETE FROM EMP WHERE CITY = "Santacruz";
SAVEPOINT C;

ROLLBACK TO SAVEPOINT A;
ROLLBACK TO SAVEPOINT B;
ROLLBACK TO SAVEPOINT C;



CREATE VIEW EMPVIEW AS SELECT EID, ENAME, DEPT, SALARY FROM EMP;

SELECT * FROM EMPVIEW;
ROLLBACK;

DELETE FROM EMPVIEW WHERE EID = 3030;
INSERT INTO EMPVIEW VALUES 
(3030, 'Sam', "MLE",2529502),
(3031, 'Richard III', "ME",2529502),
(3032, 'Bush II', "Managment",2529502),
(3033, 'Marcus', "HR",2529502);

DESCRIBE EMP;
DESCRIBE EMPVIEW;

UPDATE EMPVIEW SET ENAME = "Suhani" WHERE EID =3031;
ROLLBACK;

-- COMPLEX VIEW

CREATE VIEW EMPDEPTVIEW AS SELECT EID, ENAME, EMP.DEPT, SALARY FROM EMP INNER JOIN DEPARTMENT D ON EMP.DEPT = D.DEPT;
DROP VIEW EMPDEPTVIEW;
UPDATE EMPDEPTVIEW SET DEPT = "Finance" WHERE ename = "Tirth";
UPDATE EMPDEPTVIEW SET DEPT = "IT" WHERE ID = 4;


select * from EMP;
CREATE VIEW EMPDEPTVIEW_1 AS SELECT EID, ENAME, EMP.DEPT, SALARY FROM EMP INNER JOIN DEPARTMENT D ON EMP.DEPT = D.DEPT;
CREATE VIEW EMPDEPTV AS SELECT ID, DEPT, DEPT_NAME FROM DEPARTMENT;
DESCRIBE EMPDEPTV;
CREATE VIEW EDVIEW AS SELECT EID, ENAME,  ID, D.DEPT,DEPT_NAME, SALARY FROM EMP INNER JOIN DEPARTMENT D ON EMP.DEPT = D.DEPT;

DESCRIBE EDVIEW;

UPDATE EDVIEW SET DEPT_NAME= "IT" WHERE ENAME = "Sam";

SELECT * FROM EMP;
SELECT * FROM EDVIEW;
SELECT * FROM DEPARTMENT;

SET AUTOCOMMIT = 1;
DROP VIEW EDVIEW;

INSERT INTO DEPARTMENT VALUES 
(6, "HR", "Human Resource"),
(7, "BOARD", "Board of Directors"),
(8, "COF", "Chief of Finance"),
(9, "COS", "Chief of Staff"),
(10, "COA", "Chief of Associates");



