USE EMPDB;
SELECT * FROM EMP;

#Q1
SELECT MAX(SALARY) FROM EMP; # 5329500
SELECT ENAME FROM EMP WHERE SALARY >= 5329500;

#Q2
-- COREELLATED QUERY
SELECT * FROM EMP WHERE SALARY >= ALL (SELECT MAX(SALARY) FROM EMP);



