SHOW DATABASES;
USE MASTERCHEF;
SHOW TABLES;
SELECT * FROM COOK;
SELECT * FROM RECIPE;
SELECT * FROM INGREDIENTS;

SELECT * FROM COOK INNER JOIN RECIPE ON COOK.FOOD_ID = RECIPE.FOOD_ID ;
SELECT c.EMP_ID, COUNT(DISTINCT r.INGRI_ID) AS ingredient_count FROM COOK c INNER JOIN RECIPE r ON c.FOOD_ID = r.FOOD_ID GROUP BY c.EMP_ID ORDER BY ingredient_count DESC LIMIT 3;