CREATE DATABASE NEW_DATA;
USE NEW_DATA;

CREATE TABLE Employee (
	employee_id INT PRIMARY KEY, 
    EMPLOYEE_NAME VARCHAR(100),
    EMPLOYEE_SALARY INT,
    DEPARTMENT VARCHAR(100));
    

DESCRIBE EMPLOYEE;

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT) VALUES
(1, 'Kartik', 50000,'Engineering'),
(2, 'Pratik', 60000,'HR'),
(3, 'Satvik', 70000,'SALES'),
(4, 'Moliti', 80000,'Staff'),
(5, 'Rutvik', 90000,'Staff 1'),
(6, 'Hrithvik', 100000,'Staff 2'),
(7, 'Tirth', 120000,'Staff 3'),
(8, 'Vansh', 130000,'Staff 4'),
(9, 'Arnav', 150000,'Staff 5'),
(10, 'Gopal', 160000,'Staff 6');

SELECT * FROM EMPLOYEE;

DELIMITER //

CREATE PROCEDURE BONUS_SALARIES()
BEGIN
	DECLARE DONE INT DEFAULT FALSE;
	DECLARE EMP_ID INT;
    DECLARE EMP_SALARY VARCHAR(100);
    DECLARE EMP_NAME VARCHAR(100);
    DECLARE DEPT VARCHAR(100);
    
    DECLARE ECURSOR CURSOR FOR
    SELECT EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT FROM EMPLOYEE;
    
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    
    OPEN ECURSOR;
    PRINT_ : LOOP
		FETCH ECURSOR INTO EMP_ID, EMP_NAME, EMP_SALARY, DEPT;
        
        IF DONE THEN 
        LEAVE PRINT_;
        END IF;
        
        UPDATE EMPLOYEE
        SET EMPLOYEE_SALARY = EMP_SALARY * 1.1 WHERE EMPLOYEE_ID = EMP_ID;
        END LOOP;
        
        CLOSE ECURSOR;
        END //
        
DELIMITER ;

DROP PROCEDURE BONUS_SALARIES;

CALL BONUS_SALARIES();

SELECT * FROM EMPLOYEE;
