USE EMPDB;

DELIMITER //

CREATE FUNCTION MULTIPLY (A INT, B INT)
RETURNS INT
DETERMINISTIC
BEGIN 
	DECLARE OUT_MULTIPLY INT;
	SET OUT_MULTIPLY = A * B;
    RETURN OUT_MULTIPLY;
    
END //

DELIMITER ;

# DROP FUNCTION MULTIPLY;

SELECT MULTIPLY (2,4);

DELIMITER BIGBANG

CREATE FUNCTION CUST_OCCUPATION (AGE INT)
RETURNS VARCHAR(30)
DETERMINISTIC
BEGIN 
	DECLARE OCC VARCHAR(20);
		IF(AGE > 25) THEN
			SET OCC = "DX Engineer";
			
            ELSEIF (AGE <= 35 AND AGE >= 30) THEN 
				SET  OCC = "Doctor";
			
            ELSEIF(AGE < 30 ) THEN
				SET OCC = "INVESTOR";
            
            END IF;
				RETURN OCC;
            
END BIGBANG
DELIMITER ;

SELECT CUST_OCCUPATION (40);

DELIMITER BIGBANG

CREATE FUNCTION CO_STRING (S1 VARCHAR(20), S2 VARCHAR(20))
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN 
	DECLARE RESULT VARCHAR(50);
	# CONCAT FUNCTION MUST BE USED.
	SET RESULT = CONCAT(S1,S2);
	RETURN RESULT;
            
END BIGBANG
DELIMITER ;

SELECT CO_STRING ('CDAC_', 'CHENNAI');

DROP FUNCTION CO_STRING;


CREATE TABLE  STD_MARKS(SID INT, SNAME VARCHAR(50), MATHS_MARKS FLOAT, CHEMISRTY_MARKS FLOAT, BIOLOGY_MARKS FLOAT, HISTORY_MARKS FLOAT, GEOGRAPHY_MAKRS FLOAT);

INSERT INTO STD_MARKS VALUES 
(101, "Parvati", 90,34,24,44,21),
(102, "Shreyta", 44,88,90,98,82),
(103, "Shruti", 22,59,81,90,98);

SELECT * FROM STD_MARKS;

DELIMITER $$
CREATE FUNCTION TOTAL_MARKS(ID INT)
RETURNS FLOAT
DETERMINISTIC
BEGIN 
	DECLARE TOTAL FLOAT;
    DECLARE AVERAGE FLOAT;
	DECLARE M1 INT;
    DECLARE M2 INT;
    DECLARE M3 INT;
    DECLARE M4 INT;
    DECLARE M5 INT;
    SELECT  MATHS_MARKS, CHEMISRTY_MARKS, BIOLOGY_MARKS, HISTORY_MARKS , GEOGRAPHY_MAKRS INTO M1, M2, M3, M4, M5 FROM STD_MARKS WHERE SID = ID;
    # SELECT  SUM(MATHS_MARKS + CHEMISRTY_MARKS + BIOLOGY_MARKS + HISTORY_MARKS + GEOGRAPHY_MAKRS) INTO TOTAL  FROM STD_MARKS WHERE SID = ID;
    SET TOTAL = M1 + M2 + M3 + M4 + M5;
    SET AVERAGE = (TOTAL/5);
	RETURN AVERAGE;
END $$

DELIMITER ;
DROP FUNCTION TOTAL_MARKS;
SELECT TOTAL_MARKS(103);

/*
DELIMITER //

CREATE FUNCTION CAL_INCOME(SALARY INT);
RETURNS INT
DETERMINISTIC
BEGIN 
	DECLARE INCOME INT;
	SET INCOME = 0;
    LABEL:
		WHILE INCOME <= 1000 DO 
			SET 
END //

*/



