show DATABASES ;
show tables;
SELECT * FROM COMPANIES;
SELECT * FROM DUPE;
SELECT * FROM INTOSHUSERS;
SELECT * FROM INTOSHDATA;
CREATE TABLE INTOSHDATA (USERNAME VARCHAR(100), MACHINE VARCHAR(100));
INSERT INTO INTOSHDATA VALUES ("imonish8", "Dell");
INSERT INTO INTOSHDATA VALUES ("MN8", "Mac");
INSERT INTO INTOSHDATA VALUES ("NEEL8", "HP");
INSERT INTO INTOSHDATA VALUES ("KARAN8", "LENOVO");

SELECT * FROM INTOSHDATA JOIN INTOSHUSERS ON INTOSHUSERS.USERNAME = INTOSHDATA.USERNAME;
SELECT INTOSHDATA.MACHINE, SUM(PASSSCODE) FROM INTOSHUSERS JOIN INTOSHDATA ON INTOSHUSERS.USERNAME = INTOSHDATA.USERNAME GROUP BY INTOSHDATA.MACHINE;