SHOW DATABASES;
USE EMPDB;
CREATE TABLE CUSTOMER (C_ID INT NOT NULL PRIMARY KEY, C_NAME VARCHAR (20), C_NUM INT , C_PAY VARCHAR(20), C_AMT INT);
INSERT INTO CUSTOMER VALUES
(1, 'Nikhil',21,'Rent', 4000),
(2, 'Rana',24,'uuu',5000),
(3, 'Naren',23,'maintain', 6000),
(4, 'Saniya',25,'Rent', 4000),
(5,'chikhil',26,'Rent', 4000);
DESCRIBE CUSTOMER;
SELECT * FROM CUSTOMER;
SELECT C_NAME FROM CUSTOMER WHERE C_AMT = (SELECT MAX(C_AMT) FROM CUSTOMER);
SELECT C_NAME FROM CUSTOMER WHERE C_AMT > (SELECT AVG(C_AMT) FROM CUSTOMER);
CREATE TABLE ORDERS (orderid int not null primary key, custnum int, status varchar(10), ordernum int, budget int);
ALTER TABLE ORDERS CHANGE CUSTNUM C_NUM INT;
DESC ORDERS;

INSERT INTO ORDERS VALUES
(01, 21, 'done', 2022, 4000),
(02, 23, 'done', 2023,5000),
(03, 25, 'done', 2024, 4000);
SELECT * FROM ORDERS;
SELECT CUSTOMER.C_NAME, ORDERS.ORDERID FROM CUSTOMER LEFT JOIN ORDERS ON CUSTOMER.C_NUM = ORDERS.C_NUM WHERE ORDERID IS NULL;
SELECT MIN(BUDGET) FROM ORDERS;
SELECT MAX(BUDGET) FROM ORDERS;
SELECT AVG(BUDGET) FROM ORDERS;
SELECT MIN(C_AMT) FROM CUSTOMER;
SELECT MAX(C_AMT) FROM CUSTOMER;
SELECT AVG(C_AMT) FROM CUSTOMER;
